openapi: 3.0.0
servers:
  - url: https://gateway.jamma.cn/passport/weapp
info:
  version: "1.0.0"
  title: wechat-user-api
  description: 微信用户服务，依赖user服务
paths:
  /signon/mp:
    description: 公众号用户登陆
    post:
      responses:
        '200':
          description: 登陆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
  /signon/weapp:
    description: 微信小程序用户登陆
    post:
      responses:
        '200':
          description: 登陆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
components:
  schemas:
    LoginInfo:
      type: object
      properties:
        unionid:
          type: string
        openid:
          type: string
      description: 登陆信息
    UserInfo:
      type: object
      properties:
        id:
          type: string
          example: '596d5cb3baeeaf00203de4ec'
